#!/bin/bash
cd "$(dirname "$0")" || exit

echo "⏳ Preparando ambiente..."
echo "--------------------------"

if ! command -v python3 &> /dev/null; then
    echo "⚠️ Python3 não encontrado, instalando..."
    sudo apt update && sudo apt install -y python3 python3-pip
fi

echo "📦 Instalando dependências..."
python3 -m pip install --upgrade pip --user
python3 -m pip install xmltodict openpyxl --user

echo ""
echo "🚀 Rodando o programa..."
echo "--------------------------"
python3 robo_nf.py

echo "--------------------------"
echo "✅ FIM!"
read -p "Aperte ENTER para fechar..."

